os: linux

before_install:
  - sudo apt-get install -y texlive-full
  - chmod +x blog_push.sh


script:
  # build the cv
  - make

after_success:
  - if [ "$TRAVIS_BRANCH" = "cv-v2" ]; then ./blog_push.sh; fi
