name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          root_file: cv.tex
      - name: Add to release
        uses: actions/upload-artifact@v1
        with:
          name: cv-${GITHUB_SHA::8}
          path: cv.pdf
